language: node_js
sudo: false
node_js:
  - "9.3"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run demo:build
after_success:
  - npm run coverage
  # deploy site
  - chmod +x demo/deploy.sh
  - bash demo/deploy.sh
  # deploy stack blitz repo
  - chmod +x demo/stackblitz.sh
  - bash demo/stackblitz.sh
  # deploy dist
  - chmod +x demo/dist-deploy.sh
  - bash demo/dist-deploy.sh
