language: node_js
sudo: false
node_js:
  - "9.3"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run aio:build
after_success:
  - npm run coverage
  - chmod +x bash ./aio/deploy-ghpages.sh
