language: node_js
sudo: false
node_js:
  - "9.3"
install:
  - npm install
script:
  - npm run lint
  - npm test
after_success:
  - npm run coverage
  - chmod +x deploy.sh
  - export DEPLOY_TARGET_REPO_DIST=demo && export DEPLOY_TARGET_REPO_GH_PAGES=gh-pages && bash deploy.sh
