language: node_js
sudo: false
node_js:
  - "9.3"
branches:
    except:
    - sandbox
    - gh-pages
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run demo:build
after_success:
  - npm run coverage
  - chmod +x deploy.sh
  - export DEPLOY_TARGET_REPO_DIST=sandbox && export DEPLOY_TARGET_REPO_GH_PAGES=gh-pages && bash deploy.sh
