language: node_js
sudo: false
node_js:
  - "9.3"
install:
  - npm install
script:
  - npm run lint
  - npm test
after_success:
  - npm run coverage
  - chmod +x deploy.sh
  - cp deploy.sh demo/
  - export DEPLOY_TARGET_BRANCH=demo && export BASE_PATH=demo && bash deploy.sh
